### PR TITLE
Remove redundant pinning of memory [io_uring]

### PR DESCRIPTION
**Pull request by tkp1n**
It appears to me as if the recent improvements regarding linked operations in the `io_uring` case #67 introduced a subtle bug:

1. The `Memory<byte>` kept per operation is pinned twice, once when submitting the poll, once when submitting the actual read/write.
2. The local counter variable `sqesAvailable` is decremented by two, although both the poll and the operation itself only occupy one `sqe`.

This PR should address both issues.

PTAL @tmds @antonfirsov

### CODE REVIEW

**Comment by tmds** [comment]
Thanks! Can you also update the `(sqesAvailable > 2)` a bit higher up?

**Comment by tkp1n** [comment]
> Can you also update the `(sqesAvailable > 2)` a bit higher up?

`OperationType.Cancel` still needs 2 `sqe`s though... Should I complicate the loop further to ensure we fill every last `sqe` is possible? I don't think that would pay off...

**Comment by tmds** [comment]
> OperationType.Cancel still needs 2 sqes though.

Ah yes. Let's keep it simple.

**Comment by tmds** [comment]
Thanks for catching this!

**Pull request merged**
