### PR TITLE
Use POH for dummyreadbuffers

### PR DESCRIPTION
**Pull request by tmds**
Minor improvement. The APIs used here are new in .NET 5.

cc @antonfirsov @adamsitnik

### CODE REVIEW

**Comment by antonfirsov** [comment]
It seems it does not work yet on the server:
```
error CS0117: 'GC' does not contain a definition for 'AllocateUninitializedArray'
```

**Comment by adamsitnik** [comment]
@antonfirsov could you try `--runtimeversion 5.0.*` ? It should download the latest bits

**Comment by antonfirsov** [comment]
`--runtimeversion 5.0.*` did not help. I will ask Sebastien for support. @tmds any chance to revert this until we can make sure it works?

**Comment by adamsitnik** [comment]
@antonfirsov Could you please try to find the version of SDK and Runtime that has exposed `GC.AllocateUninitializedArray` as a public method and specifying it in an explicit way to the `BenchmarkDriver`?. Sth like:

```cmd
--runtime 5.0.0-preview.3.20173.5 --aspnetcoreversion 5.0.0-preview.3.20173.4 --sdk 5.0.100-preview.3.20174.1
```

BTW `--runtimeversion 5.0.*` is a tip I got from @sebastienros last time I've run into similar issue ;)

**Pull request merged**
