### PR TITLE
Reduce locking in EPollAsyncEngine.Queue

### PR DESCRIPTION
**Pull request by tmds**

### CODE REVIEW

**Comment by tmds** [comment]
@antonfirsov can you run the following benchmark master vs PR:
```
--arg "-e=epoll" --arg "-t=6" --arg "-s=false" --arg "-r=false" --arg "-c=false" --arg "-a=true" --arg "-w=false" --arg "-i=true" --arg "-o=inline" --connections 256
```
I would like to know if this makes a measurable difference, before continuing.

Can you also share both trace files?

cc @adamsitnik

**Comment by antonfirsov** [comment]
I've been running this with `--duration 30` to get more stable results.

```
>> master
RequestsPerSecond:           486,849
Max CPU (%):                 51
Avg. Latency (ms):           0.72

>> PR
RequestsPerSecond:           501,658
Max CPU (%):                 51
Avg. Latency (ms):           0.75
```

**UPDATE**
Almost forgot about the traces! Made a second run, with tracing enabled:
```
>> master:
RequestsPerSecond:           478,004
Max CPU (%):                 50
Avg. Latency (ms):           0.64

>> PR:
RequestsPerSecond:           486,408
Max CPU (%):                 50
Avg. Latency (ms):           0.73
```

Traces are available on [OneDrive](https://microsoft-my.sharepoint.com/:f:/p/anfirszo/EkqER0svzQlJsYVH9EXVkosBElKc2q1K2wFI4TtC4L1mpg?e=ku3P5d) in folder `ReduceLocing`.

**Comment by tmds** [comment]
I was hoping for a 1-2% improvement, and benchmarks seem to show something in that range.

> Max CPU (%):                 50

@antonfirsov This is surprisingly low. Do we know `Max CPU` for these benchmarks: https://github.com/tmds/Tmds.LinuxAsync/issues/41#issuecomment-601826631?

**Comment by antonfirsov** [comment]
With `o=iothread` and `o=inline` it's 50% even without the queue optimization.

**Comment by tmds** [comment]
@antonfirsov @adamsitnik I've also made similar changes for io_uring.
I did some runs on my machine and didn't hit any issues.

If you have some time, please take a look.

**Comment by tmds** [comment]
The interesting files to look at are `AsyncOperationQueueBase.cs` which implements a queue that doesn't need `lock` as long as it only contains at most 1 operation.

`EPollAsyncEngine.Queue.cs` and `IoUringAsyncEngine.Queue.cs` derive from this, and then use `Interlocked`/`Volatile` operations on `AsyncOperation.Status` for synchronization the operation state.

Some special care is needed for cancellation because that is triggered asynchronous. Even more for io_uring because the operations needs to be cancelled on the ring.

**Comment by tmds** [comment]
I've merged this. If you add comments/questions to the PR, I will still address them.

**Pull request merged**
