### PR TITLE
Revert "Use POH for dummyreadbuffers"

### PR DESCRIPTION
**Pull request by antonfirsov**
Temporarily reverting #83 to unblock benchmarking, should be easy to undo. I hope we can figure it out in a couple of days.

/cc @sebastienros

### CODE REVIEW

**Comment by tmds** [comment]
@davidfowl @halter73 this API is in runtime repo for 3 weeks (and 5.0 preview2). We can't figure out how to use it on the benchmark machine. Any suggestions?

cc @adamsitnik

**Comment by halter73** [comment]
Are you talking about https://github.com/dotnet/runtime/pull/33526? Sometimes it takes a while for aspnetcore to update its runtime dependency. Our internal dashboard shows we're only 3 days behind though.

You could try passing ` --runtimeVersion Latest` to the BenchmarksDriver. That doesn't wait for our dependency update flow.

**Comment by tmds** [comment]
> Our internal dashboard shows we're only 3 days behind though.

This is weeks behind.
Are we using the same machines?

**Comment by halter73** [comment]
Are you passing ` --runtimeVersion Latest` to the BenchmarksDriver?

With that flag, the aspnet/Benchmarks infrastructure is designed to support dynamically updating to the latest dotnet runtime and sdk even if no aspnetcore runtime has been successfully built agains it yet.

**Pull request merged**
